# Generated by Django 3.0.7 on 2020-07-02 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20200630_2351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='search',
            name='location',
            field=models.CharField(max_length=500),
        ),
    ]
